sh_test(
    name = "configs_test",
    srcs = ["configs_test.sh"],
    data = [
        "configs.lua",
        "configs_test.lua",
        "shlib.lua",
        "//third_party/lua",
    ],
)

sh_test(
    name = "shlib_test",
    srcs = ["shlib_test.sh"],
    data = [
        "shlib.lua",
        "shlib_test.lua",
        "//third_party/lua",
    ],
)
