#!/bin/bash
#
# Copyright 2016 The Minimal Configuration Manager Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Wrapper that autoinstalls Bazel

die() {
  echo "$@" 1>&2
  exit 1
}

WORKSPACE_DIR="$(dirname "$(readlink -f "$0")")"
BAZEL_RELEASE='0.4.0'
if [[ ! -x "$WORKSPACE_DIR/.bazel/bin/bazel" ]]; then
  echo "Downloading Bazel ${BAZEL_RELEASE}..." 1>&2
  installscript="/tmp/bazel-${BAZEL_RELEASE}.sh"
  curl -sSL "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_RELEASE}/bazel-${BAZEL_RELEASE}-installer-linux-x86_64.sh" > "$installscript" || \
    (rm -f "$installscript" ; die "bazel: wrapper: failed to download")
  bash /tmp/bazel-${BAZEL_RELEASE}.sh \
    --bin="$WORKSPACE_DIR/.bazel/bin" \
    --base="$WORKSPACE_DIR/.bazel/lib" \
    --bazelrc="$WORKSPACE_DIR/.bazel/bazelrc" || \
    (rm -f "$installscript" ; die "bazel: wrapper: failed to install")
  rm -f "$installscript"
fi
exec "$WORKSPACE_DIR/.bazel/bin/bazel" "$@"
