go_binary(
    name = "mcm-exec",
    srcs = glob(["*.go"]),
    deps = [
        "//:catalog",
        "//exec/execlib:go_default_library",
        "//third_party/golang/capnproto:go_default_library",
    ],
)
