package(default_visibility = ["//:__subpackages__"])

go_default_library(
    test = 1,
    deps = [
        "//:catalog",
    ],
    test_deps = [
        "//:catalog",
        "//third_party/golang/capnproto:go_default_library",
        "//third_party/golang/capnproto:pogs",
    ],
)
