package(default_visibility = ["//exec:__subpackages__"])

go_default_library(
    deps = [
        "//:catalog",
        "//internal/depgraph:go_default_library",
        "//internal/system:go_default_library",
    ],
)
