package(default_visibility = ["//:__subpackages__"])

go_default_library(
    test = 1,
    testonly = 1,
    deps = [
        "//internal/system:go_default_library",
    ],
    test_deps = [
        "//internal/system:go_default_library",
    ],
)
