go_binary(
    name = "mcm-catbash",
    srcs = glob(["*.go"]),
    deps = [
        "//:catalog",
        "//internal/depgraph:go_default_library",
        "//third_party/golang/capnproto:go_default_library",
    ],
)
